config/routes.rb
#root
Rails.application.routes.draw do
 
  resources :elevators
  resources :columns
  resources :batteries
  resources :building_details
  resources :buildings
  resources :customers
  resources :addresses
  resources :leads
  root 'rocket_elevator#index'
  get '/index', to: 'rocket_elevator#index'
  get "/residancial", to: "rocket_elevator#residancial"
  get "/commercial", to: "rocket_elevator#commercial"
  get "/quote", to: "rocket_elevator#quote"
  get "/news_press1", to: "rocket_elevator#news_press1"
  get "/news_press2", to: "rocket_elevator#news_press2"
  get "/news_press3", to: "rocket_elevator#news_press3"
  get "/news_press4", to: "rocket_elevator#news_press4"
  get "/news_press5", to: "rocket_elevator#news_press5"
  get "/news_press6", to: "rocket_elevator#news_press6"
  get "/portfolio_detail_modal_1.html", to: "rocket_elevators#portfolio_detail_modal_1"




  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html

       devise_for :users
      mount RailsAdmin::Engine => '/', as: 'rails_admin'
  
  
      namespace :api, defaults: {format: :json} do
        namespace :v1 do 
           devise_scope :user do
              #post "sign_up", to: "registrations#/admin"
               post "sign_in", to: "main#/admin"
           end
         end
       end
end

app/models/ability.rb
# frozen_string_literal: true

class Ability
  include CanCan::Ability

  def initialize(user)
    # Define abilities for the passed in user here. For example:
    #
      user ||= User.new # guest user (not logged in)
      if user.admin?
         can :manage, :all
       else
         can :read, :all
       end
    #
    # The first argument to `can` is the action you are giving the user
    # permission to do.
    # If you pass :manage it will apply to every action. Other common actions
    # here are :read, :create, :update and :destroy.
    #
    # The second argument is the resource the user can perform the action on.
    # If you pass :all it will apply to every resource. Otherwise pass a Ruby
    # class of the resource.
    #
    # The third argument is an optional hash of conditions to further filter the
    # objects.
    # For example, here the user can only update published articles.
    #
    #   can :update, Article, :published => true
    #
    # See the wiki for details:
    # https://github.com/CanCanCommunity/cancancan/wiki/Defining-Abilities
  end
end

app/models/address.rb
class Address < ApplicationRecord
end

app/models/battery.rb
class Battery < ApplicationRecord
  belongs_to :building
  belongs_to :employee

  has_many :column
end

app/models/building.rb
class Building < ApplicationRecord
  belongs_to :customer
  belongs_to :address

  has_one :building_detail
  has_many :battery
end

app/models/building_detail.rb
class BuildingDetail < ApplicationRecord
  belongs_to :building
end

app/models/column.rb
class Column < ApplicationRecord
  belongs_to :battery
  has_many :elevator
end

app/models/customer.rb
class Customer < ApplicationRecord
belongs_to :address

has_many :building
end

app/models/elevator.rb
class Elevator < ApplicationRecord
  belongs_to :column
  has_many :elevator

  def userid
    return self.Column.battery.building.customer.user.id
  end
end

app/models/employee.rb
class Employee < ApplicationRecord
  has_one :user
  has_one :battery
end

app/models/lead.rb
class Lead < ApplicationRecord


end

app/models/quote.rb
class Quote < ApplicationRecord
end

app/models/user.rb
class User < ActiveRecord::Base
  has_one :customer
  belongs_to :employee, optional: true
  #acts_as_token_authenticatable
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
         # app/models/user.rb    
def admin?
    admin
end
end

app/controllers/buildings_controller.rb
class BuildingsController < ApplicationController
  before_action :set_building, only: [:show, :edit, :update, :destroy]

  # GET /buildings
  # GET /buildings.json
  def index
    @buildings = Building.all
  end

  # GET /buildings/1
  # GET /buildings/1.json
  def show
  end

  # GET /buildings/new
  def new
    @building = Building.new
  end

  # GET /buildings/1/edit
  def edit
  end

  # POST /buildings
  # POST /buildings.json
  def create
    @building = Building.new(building_params)

    respond_to do |format|
      if @building.save
        format.html { redirect_to @building, notice: 'Building was successfully created.' }
        format.json { render :show, status: :created, location: @building }
      else
        format.html { render :new }
        format.json { render json: @building.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /buildings/1
  # PATCH/PUT /buildings/1.json
  def update
    respond_to do |format|
      if @building.update(building_params)
        format.html { redirect_to @building, notice: 'Building was successfully updated.' }
        format.json { render :show, status: :ok, location: @building }
      else
        format.html { render :edit }
        format.json { render json: @building.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /buildings/1
  # DELETE /buildings/1.json
  def destroy
    @building.destroy
    respond_to do |format|
      format.html { redirect_to buildings_url, notice: 'Building was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_building
      @building = Building.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def building_params
      params.require(:building).permit(:customer_id, :address_id, :full_name_of_building_administrator, :email_of_building_administrator, :phone_of_building_administrator, :full_name_technical_contact, :technical_contact_email, :technical_contact_phone)
    end
end

app/helpers/addresses_helper.rb
module AddressesHelper
end

app/helpers/admin_helper.rb
module AdminHelper
end

app/helpers/batteries_helper.rb
module BatteriesHelper
end

app/helpers/buildings_helper.rb
module BuildingsHelper
end

app/helpers/columns_helper.rb
module ColumnsHelper
end

app/helpers/leads_helper.rb
module LeadsHelper
end

app/helpers/pages_helper.rb
module PagesHelper
end

app/helpers/quotes_helper.rb
module QuotesHelper
end

app/helpers/startup_helper.rb
module StartupHelper
end

app/helpers/welcome_helper.rb
module WelcomeHelper
end

app/views/buildings/_form.html.erb
<%= form_with(model: building, local: true) do |form| %>
  <% if building.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(building.errors.count, "error") %> prohibited this building from being saved:</h2>

      <ul>
      <% building.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label :customer_id %>
    <%= form.text_field :customer_id %>
  </div>

  <div class="field">
    <%= form.label :address_id %>
    <%= form.text_field :address_id %>
  </div>

  <div class="field">
    <%= form.label :full_name_of_building_administrator %>
    <%= form.text_field :full_name_of_building_administrator %>
  </div>

  <div class="field">
    <%= form.label :email_of_building_administrator %>
    <%= form.text_field :email_of_building_administrator %>
  </div>

  <div class="field">
    <%= form.label :phone_of_building_administrator %>
    <%= form.number_field :phone_of_building_administrator %>
  </div>

  <div class="field">
    <%= form.label :full_name_technical_contact %>
    <%= form.text_field :full_name_technical_contact %>
  </div>

  <div class="field">
    <%= form.label :technical_contact_email %>
    <%= form.text_field :technical_contact_email %>
  </div>

  <div class="field">
    <%= form.label :technical_contact_phone %>
    <%= form.number_field :technical_contact_phone %>
  </div>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

app/views/buildings/edit.html.erb
<h1>Editing Building</h1>

<%= render 'form', building: @building %>

<%= link_to 'Show', @building %> |
<%= link_to 'Back', buildings_path %>

app/views/buildings/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Buildings</h1>

<table>
  <thead>
    <tr>
      <th>Customer</th>
      <th>Address</th>
      <th>Full name of building administrator</th>
      <th>Email of building administrator</th>
      <th>Phone of building administrator</th>
      <th>Full name technical contact</th>
      <th>Technical contact email</th>
      <th>Technical contact phone</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @buildings.each do |building| %>
      <tr>
        <td><%= building.customer %></td>
        <td><%= building.address %></td>
        <td><%= building.full_name_of_building_administrator %></td>
        <td><%= building.email_of_building_administrator %></td>
        <td><%= building.phone_of_building_administrator %></td>
        <td><%= building.full_name_technical_contact %></td>
        <td><%= building.technical_contact_email %></td>
        <td><%= building.technical_contact_phone %></td>
        <td><%= link_to 'Show', building %></td>
        <td><%= link_to 'Edit', edit_building_path(building) %></td>
        <td><%= link_to 'Destroy', building, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Building', new_building_path %>

app/views/buildings/new.html.erb
<h1>New Building</h1>

<%= render 'form', building: @building %>

<%= link_to 'Back', buildings_path %>

app/views/buildings/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Customer:</strong>
  <%= @building.customer %>
</p>

<p>
  <strong>Address:</strong>
  <%= @building.address %>
</p>

<p>
  <strong>Full name of building administrator:</strong>
  <%= @building.full_name_of_building_administrator %>
</p>

<p>
  <strong>Email of building administrator:</strong>
  <%= @building.email_of_building_administrator %>
</p>

<p>
  <strong>Phone of building administrator:</strong>
  <%= @building.phone_of_building_administrator %>
</p>

<p>
  <strong>Full name technical contact:</strong>
  <%= @building.full_name_technical_contact %>
</p>

<p>
  <strong>Technical contact email:</strong>
  <%= @building.technical_contact_email %>
</p>

<p>
  <strong>Technical contact phone:</strong>
  <%= @building.technical_contact_phone %>
</p>

<%= link_to 'Edit', edit_building_path(@building) %> |
<%= link_to 'Back', buildings_path %>